#ifndef clox_common_h
#define clox_common_h

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* Flag for Dumping Chunks 
 *
 * To help debug the generated bytecode, 
 * add support for dumping the chunk once the compiler finishes. 
 * Had some temporary logging earlier when hand-authored the chunk. */
#define DEBUG_PRINT_CODE


#define UINT8_COUNT (UINT8_MAX + 1)

/* First create a flag to hide the diagnostic logging behind.
 *
 * When this flag is defined, 
 * the VM disassembles and prints each instruction right 
 * before executing it. */
#define DEBUG_TRACE_EXECUTION

#endif
